### PR TITLE
Update ml-javaclient-util for .SJS

### PR DESCRIPTION
**Pull request by lewisap**
Updated to process server side javascript files for modules and REST endpoints for ML8.

### CODE REVIEW

**Comment by rjrudin** [comment]
Hey Adam - can you confirm that the 3.0.1 instance of the Java API will still work with MarkLogic 7? Best way to do that I think is to try it on OBI - update OBI to use 3.0.1 (via its build.gradle file), then run "gradle eclipse test" to see if all the tests pass. 

We're not doing anything very fancy with the Java API, so I imagine 3.0.1 is fine, but I don't want to break anything with ML7.

**Comment by rjrudin** [comment]
Also, I think XmlExtensionMetadataProvider will work fine for JS modules, it just needs a little tweaking. It should say something like - If this module ends in .js or .sjs, then set the script language to JS. Otherwise, all it's doing is processing the metadata/(name of resource).xml file that is used for documentation purposes. That would also remove the if/else statements for changing the implementation of ExtensionMetadataProvider.

**Comment by lewisap** [comment]
I didn't get a chance today to check the backwards compatibility of the ML
Java API with ML7.   I'll be doing that tomorrow.

In regards to using the XmlExtensionMetadataProvider for both .xqy and .sjs
files, I disagree.   The naming of the class strongly implies it should be
used for .xqy files only.  That, and I wasn't sure what other functionality
might have been created for .sjs files as well; so I felt it best to split
them out.  I do agree on the clumsy nature of the if/else statements, and
had given the thought of creating a factory method that would create the
correct implementation class based on the file (and thereby the
extension).  I just didn't get around to it, and wanted folks to have
something that works for server side javascript to play with.

On Mon, Feb 16, 2015 at 9:23 PM, rjrudin <notifications@github.com> wrote:

> Also, I think XmlExtensionMetadataProvider will work fine for JS modules,
> it just needs a little tweaking. It should say something like - If this
> module ends in .js or .sjs, then set the script language to JS. Otherwise,
> all it's doing is processing the metadata/(name of resource).xml file that
> is used for documentation purposes. That would also remove the if/else
> statements for changing the implementation of ExtensionMetadataProvider.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/rjrudin/ml-javaclient-util/pull/5#issuecomment-74607742>
> .
>



-- 
-Adam Lewis

**Comment by rjrudin** [comment]
The "Xml" in XmlExtensionMetadataProvider only refers to the content of the metadata file. That metadata file could be used for an XQuery module or a JS module. 

But I definitely see how it's a misleading name. The first two words - "XmlExtension" - certainly suggest that this code is for an XQuery module. "Extension" actually goes with "Metadata" - this class provides extension metadata via an XML file.

There's always the standby of "DefaultExtensionMetadataProvider" - thoughts on that? I still prefer a single class, where the responsibility of the class is providing extension metadata for an extension, regardless of whether it's XQuery or JS.

**Comment by lewisap** [comment]
Ok, so I just combined the functionality of the XmlExtensionMetadataProvider
and the JavascriptExtensionMetadataProvider into a
DefaultExtensionMetadataProvider
class.   I've verified it seems to have the appropriate behavior that I
wanted, just in a consolidated class.

I've also tested this functionality against the most recent version of ML7,
as well as ML8 with no errors at all.   This was tested against OBI btw.

I'll be checking in the code in a few minutes and creating a new pull
request (?).

On Tue, Feb 17, 2015 at 8:35 AM, rjrudin <notifications@github.com> wrote:

> The "Xml" in XmlExtensionMetadataProvider only refers to the content of
> the metadata file. That metadata file could be used for an XQuery module or
> a JS module.
>
> But I definitely see how it's a misleading name. The first two words -
> "XmlExtension" - certainly suggest that this code is for an XQuery module.
> "Extension" actually goes with "Metadata" - this class provides extension
> metadata via an XML file.
>
> There's always the standby of "DefaultExtensionMetadataProvider" -
> thoughts on that? I still prefer a single class, where the responsibility
> of the class is providing extension metadata for an extension, regardless
> of whether it's XQuery or JS.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/rjrudin/ml-javaclient-util/pull/5#issuecomment-74668053>
> .
>



-- 
-Adam Lewis

**Comment by lewisap** [comment]
I'm seeing that your build is failing for some reason (
https://travis-ci.org/rjrudin/ml-javaclient-util) .  I ran the same steps
by hand, and everything seems to compile and test properly.  Maybe a config
issue on Travis CI?

On Mon, Feb 23, 2015 at 11:13 AM, rjrudin <notifications@github.com> wrote:

> Merged #5 <https://github.com/rjrudin/ml-javaclient-util/pull/5>.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/rjrudin/ml-javaclient-util/pull/5#event-240241700>.
>



-- 
-Adam Lewis

**Pull request merged**
